const CREATE = 'CREATE';
const UPDATE = 'UPDATE';
const DELETE = 'DELETE';
const FETCH_ALL = 'FETCH_ALL';
const FETCH_POST = 'FETCH_POST';
const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';

const AUTH = 'AUTH';
const LOGOUT = 'LOGOUT';

const START_LOADING = 'START_LOADING';
const END_LOADING = 'LOADING';

module.exports = {
  CREATE,
  UPDATE,
  DELETE,
  FETCH_ALL,
  FETCH_POST,
  FETCH_BY_SEARCH,
  AUTH,
  LOGOUT,
  START_LOADING,
  END_LOADING,
};
